In [29]:
import pandas as pd
import numpy as np

In [30]:
import matplotlib.pyplot as plt
import seaborn as sns

AttributeError: module 'matplotlib' has no attribute 'get_data_path'

In [2]:
df1=pd.read_csv("D:/My_project/Titanic/Data/Raw/train.csv")
df2=pd.read_csv("D:/My_project/Titanic/Data/Raw/test.csv")
df3=pd.read_csv("D:/My_project/Titanic/Data/Raw/gender_submission.csv")

In [6]:
df1.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [7]:
df2.head(10)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

In [5]:
df3.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [10]:
df1.shape
df1.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [11]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [12]:
df1.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
PassengerId,891.0,NaN,NaN,NaN,446.0,257.353842,1.0,223.5,446.0,668.5,891.0
Survived,891.0,NaN,NaN,NaN,0.383838,0.486592,0.0,0.0,0.0,1.0,1.0
Pclass,891.0,NaN,NaN,NaN,2.308642,0.836071,1.0,2.0,3.0,3.0,3.0
Name,891,891,"Braund, Mr. Owen Harris",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sex,891,2,male,577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,714.0,NaN,NaN,NaN,29.699118,14.526497,0.42,20.125,28.0,38.0,80.0
SibSp,891.0,NaN,NaN,NaN,0.523008,1.102743,0.0,0.0,0.0,1.0,8.0
Parch,891.0,NaN,NaN,NaN,0.381594,0.806057,0.0,0.0,0.0,0.0,6.0
Ticket,891,681,347082,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fare,891.0,NaN,NaN,NaN,32.204208,49.693429,0.0,7.9104,14.4542,31.0,512.3292
Cabin,204,147,G6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Embarked,889,3,S,644,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df1.isnull().sum().sort_values(ascending=False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
Pclass           0
Survived         0
Sex              0
Parch            0
SibSp            0
Fare             0
Ticket           0
dtype: int64

In [14]:
df1.nunique().sort_values()

Survived         2
Sex              2
Pclass           3
Embarked         3
Parch            7
SibSp            7
Age             88
Cabin          147
Fare           248
Ticket         681
PassengerId    891
Name           891
dtype: int64

In [22]:
import sys
print(sys.executable)
print(sys.version)
%pip show matplotlib

c:\python314\python.exe
3.14.5 (tags/v3.14.5:5607950, May 10 2026, 10:43:50) [MSC v.1944 64 bit (AMD64)]
Name: matplotlib
Version: 3.10.8
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: Unknown <matplotlib-users@python.org>
License: License agreement for matplotlib versions 1.3.0 and later
 =========================================================

 1. This LICENSE AGREEMENT is between the Matplotlib Development Team
 ("MDT"), and the Individual or Organization ("Licensee") accessing and
 otherwise using matplotlib software in source or binary form and its
 associated documentation.

 2. Subject to the terms and conditions of this License Agreement, MDT
 hereby grants Licensee a nonexclusive, royalty-free, world-wide license
 to reproduce, analyze, test, perform and/or display publicly, prepare
 derivative works, distribute, and otherwise use matplotlib
 alone or in any derivative version, provided, however, that MDT's
 License Agreement and MDT's notice of copyright, i.e., "Copyright (c)
 2012- Matplotlib Development Team; All Rights Reserved" are retained in
 matplotlib  alone or in any derivative version prepared by
 Licensee.

 3. In the event Licensee prepares a derivative work that is based on or
 incorporates matplotlib or any part thereof, and wants to
 make the derivative work available to others as provided herein, then
 Licensee hereby agrees to include in any such work a brief summary of
 the changes made to matplotlib .

 4. MDT is making matplotlib available to Licensee on an "AS
 IS" basis.  MDT MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
 IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, MDT MAKES NO AND
 DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS
 FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB
 WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.

 5. MDT SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB
  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR
 LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING
 MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF
 THE POSSIBILITY THEREOF.

 6. This License Agreement will automatically terminate upon a material
 breach of its terms and conditions.

 7. Nothing in this License Agreement shall be deemed to create any
 relationship of agency, partnership, or joint venture between MDT and
 Licensee.  This License Agreement does not grant permission to use MDT
 trademarks or trade name in a trademark sense to endorse or promote
 products or services of Licensee, or any third party.

 8. By copying, installing or otherwise using matplotlib ,
 Licensee agrees to be bound by the terms and conditions of this License
 Agreement.

 License agreement for matplotlib versions prior to 1.3.0
 ========================================================

 1. This LICENSE AGREEMENT is between John D. Hunter ("JDH"), and the
 Individual or Organization ("Licensee") accessing and otherwise using
 matplotlib software in source or binary form and its associated
 documentation.

 2. Subject to the terms and conditions of this License Agreement, JDH
 hereby grants Licensee a nonexclusive, royalty-free, world-wide license
 to reproduce, analyze, test, perform and/or display publicly, prepare
 derivative works, distribute, and otherwise use matplotlib
 alone or in any derivative version, provided, however, that JDH's
 License Agreement and JDH's notice of copyright, i.e., "Copyright (c)
 2002-2011 John D. Hunter; All Rights Reserved" are retained in
 matplotlib  alone or in any derivative version prepared by
 Licensee.

 3. In the event Licensee prepares a derivative work that is based on or
 incorporates matplotlib  or any part thereof, and wants to
 make the derivative work available to others as provided herein, then
 Licensee hereby agrees to include in any such work a brief summary of
 the changes made to matplotlib.

 4. JDH is making matplotlib  available to Licensee on an "AS
 IS" basis.  JDH MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR
 IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, JDH MAKES NO AND
 DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS
 FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB
 WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.

 5. JDH SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB
  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR
 LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING
 MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF
 THE POSSIBILITY THEREOF.

 6. This License Agreement will automatically terminate upon a material
 breach of its terms and conditions.

 7. Nothing in this License Agreement shall be deemed to create any
 relationship of agency, partnership, or joint venture between JDH and
 Licensee.  This License Agreement does not grant permission to use JDH
 trademarks or trade name in a trademark sense to endorse or promote
 products or services of Licensee, or any third party.

 8. By copying, installing or otherwise using matplotlib,
 Licensee agrees to be bound by the terms and conditions of this License
 Agreement.
 ----

 This binary distrubution of Matplotlib can also bundle the following software
 (depending on the build):

 Name: AMS Fonts
 Files: matplotlib/tests/cmr10.pfb
 Description: Type-1 version of one of Knuth's Computer Modern fonts
 License: OFL-1.1
   The cmr10.pfb file is a Type-1 version of one of Knuth's Computer Modern fonts.
   It is included here as test data only, but the following license applies.

   Copyright (c) 1997, 2009, American Mathematical Society (http://www.ams.org).
   All Rights Reserved.

   "cmb10" is a Reserved Font Name for this Font Software.
   "cmbsy10" is a Reserved Font Name for this Font Software.
   "cmbsy5" is a Reserved Font Name for this Font Software.
   "cmbsy6" is a Reserved Font Name for this Font Software.
   "cmbsy7" is a Reserved Font Name for this Font Software.
   "cmbsy8" is a Reserved Font Name for this Font Software.
   "cmbsy9" is a Reserved Font Name for this Font Software.
   "cmbx10" is a Reserved Font Name for this Font Software.
   "cmbx12" is a Reserved Font Name for this Font Software.
   "cmbx5" is a Reserved Font Name for this Font Software.
   "cmbx6" is a Reserved Font Name for this Font Software.
   "cmbx7" is a Reserved Font Name for this Font Software.
   "cmbx8" is a Reserved Font Name for this Font Software.
   "cmbx9" is a Reserved Font Name for this Font Software.
   "cmbxsl10" is a Reserved Font Name for this Font Software.
   "cmbxti10" is a Reserved Font Name for this Font Software.
   "cmcsc10" is a Reserved Font Name for this Font Software.
   "cmcsc8" is a Reserved Font Name for this Font Software.
   "cmcsc9" is a Reserved Font Name for this Font Software.
   "cmdunh10" is a Reserved Font Name for this Font Software.
   "cmex10" is a Reserved Font Name for this Font Software.
   "cmex7" is a Reserved Font Name for this Font Software.
   "cmex8" is a Reserved Font Name for this Font Software.
   "cmex9" is a Reserved Font Name for this Font Software.
   "cmff10" is a Reserved Font Name for this Font Software.
   "cmfi10" is a Reserved Font Name for this Font Software.
   "cmfib8" is a Reserved Font Name for this Font Software.
   "cminch" is a Reserved Font Name for this Font Software.
   "cmitt10" is a Reserved Font Name for this Font Software.
   "cmmi10" is a Reserved Font Name for this Font Software.
   "cmmi12" is a Reserved Font Name for this Font Software.
   "cmmi5" is a Reserved Font Name for this Font Software.
   "cmmi6" is a Reserved Font Name for this Font Software.
   "cmmi7" is a Reserved Font Name for this Font Software.
   "cmmi8" is a Reserved Font Name for this Font Software.
   "cmmi9" is a Reserved Font Name for this Font Software.
   "cmmib10" is a Reserved Font Name for this Font Software.
   "cmmib5" is a Reserved Font Name for this Font Software.
   "cmmib6" is a Reserved Font Name for this Font Software.
   "cmmib7" is a Reserved Font Name for this Font Software.
   "cmmib8" is a Reserved Font Name for this Font Software.
   "cmmib9" is a Reserved Font Name for this Font Software.
   "cmr10" is a Reserved Font Name for this Font Software.
   "cmr12" is a Reserved Font Name for this Font Software.
   "cmr17" is a Reserved Font Name for this Font Software.
   "cmr5" is a Reserved Font Name for this Font Software.
   "cmr6" is a Reserved Font Name for this Font Software.
   "cmr7" is a Reserved Font Name for this Font Software.
   "cmr8" is a Reserved Font Name for this Font Software.
   "cmr9" is a Reserved Font Name for this Font Software.
   "cmsl10" is a Reserved Font Name for this Font Software.
   "cmsl12" is a Reserved Font Name for this Font Software.
   "cmsl8" is a Reserved Font Name for this Font Software.
   "cmsl9" is a Reserved Font Name for this Font Software.
   "cmsltt10" is a Reserved Font Name for this Font Software.
   "cmss10" is a Reserved Font Name for this Font Software.
   "cmss12" is a Reserved Font Name for this Font Software.
   "cmss17" is a Reserved Font Name for this Font Software.
   "cmss8" is a Reserved Font Name for this Font Software.
   "cmss9" is a Reserved Font Name for this Font Software.
   "cmssbx10" is a Reserved Font Name for this Font Software.
   "cmssdc10" is a Reserved Font Name for this Font Software.
   "cmssi10" is a Reserved Font Name for this Font Software.
   "cmssi12" is a Reserved Font Name for this Font Software.
   "cmssi17" is a Reserved Font Name for this Font Software.
   "cmssi8" is a Reserved Font Name for this Font Software.
   "cmssi9" is a Reserved Font Name for this Font Software.
   "cmssq8" is a Reserved Font Name for this Font Software.
   "cmssqi8" is a Reserved Font Name for this Font Software.
   "cmsy10" is a Reserved Font Name for this Font Software.
   "cmsy5" is a Reserved Font Name for this Font Software.
   "cmsy6" is a Reserved Font Name for this Font Software.
   "cmsy7" is a Reserved Font Name for this Font Software.
   "cmsy8" is a Reserved Font Name for this Font Software.
   "cmsy9" is a Reserved Font Name for this Font Software.
   "cmtcsc10" is a Reserved Font Name for this Font Software.
   "cmtex10" is a Reserved Font Name for this Font Software.
   "cmtex8" is a Reserved Font Name for this Font Software.
   "cmtex9" is a Reserved Font Name for this Font Software.
   "cmti10" is a Reserved Font Name for this Font Software.
   "cmti12" is a Reserved Font Name for this Font Software.
   "cmti7" is a Reserved Font Name for this Font Software.
   "cmti8" is a Reserved Font Name for this Font Software.
   "cmti9" is a Reserved Font Name for this Font Software.
   "cmtt10" is a Reserved Font Name for this Font Software.
   "cmtt12" is a Reserved Font Name for this Font Software.
   "cmtt8" is a Reserved Font Name for this Font Software.
   "cmtt9" is a Reserved Font Name for this Font Software.
   "cmu10" is a Reserved Font Name for this Font Software.
   "cmvtt10" is a Reserved Font Name for this Font Software.
   "euex10" is a Reserved Font Name for this Font Software.
   "euex7" is a Reserved Font Name for this Font Software.
   "euex8" is a Reserved Font Name for this Font Software.
   "euex9" is a Reserved Font Name for this Font Software.
   "eufb10" is a Reserved Font Name for this Font Software.
   "eufb5" is a Reserved Font Name for this Font Software.
   "eufb7" is a Reserved Font Name for this Font Software.
   "eufm10" is a Reserved Font Name for this Font Software.
   "eufm5" is a Reserved Font Name for this Font Software.
   "eufm7" is a Reserved Font Name for this Font Software.
   "eurb10" is a Reserved Font Name for this Font Software.
   "eurb5" is a Reserved Font Name for this Font Software.
   "eurb7" is a Reserved Font Name for this Font Software.
   "eurm10" is a Reserved Font Name for this Font Software.
   "eurm5" is a Reserved Font Name for this Font Software.
   "eurm7" is a Reserved Font Name for this Font Software.
   "eusb10" is a Reserved Font Name for this Font Software.
   "eusb5" is a Reserved Font Name for this Font Software.
   "eusb7" is a Reserved Font Name for this Font Software.
   "eusm10" is a Reserved Font Name for this Font Software.
   "eusm5" is a Reserved Font Name for this Font Software.
   "eusm7" is a Reserved Font Name for this Font Software.
   "lasy10" is a Reserved Font Name for this Font Software.
   "lasy5" is a Reserved Font Name for this Font Software.
   "lasy6" is a Reserved Font Name for this Font Software.
   "lasy7" is a Reserved Font Name for this Font Software.
   "lasy8" is a Reserved Font Name for this Font Software.
   "lasy9" is a Reserved Font Name for this Font Software.
   "lasyb10" is a Reserved Font Name for this Font Software.
   "lcircle1" is a Reserved Font Name for this Font Software.
   "lcirclew" is a Reserved Font Name for this Font Software.
   "lcmss8" is a Reserved Font Name for this Font Software.
   "lcmssb8" is a Reserved Font Name for this Font Software.
   "lcmssi8" is a Reserved Font Name for this Font Software.
   "line10" is a Reserved Font Name for this Font Software.
   "linew10" is a Reserved Font Name for this Font Software.
   "msam10" is a Reserved Font Name for this Font Software.
   "msam5" is a Reserved Font Name for this Font Software.
   "msam6" is a Reserved Font Name for this Font Software.
   "msam7" is a Reserved Font Name for this Font Software.
   "msam8" is a Reserved Font Name for this Font Software.
   "msam9" is a Reserved Font Name for this Font Software.
   "msbm10" is a Reserved Font Name for this Font Software.
   "msbm5" is a Reserved Font Name for this Font Software.
   "msbm6" is a Reserved Font Name for this Font Software.
   "msbm7" is a Reserved Font Name for this Font Software.
   "msbm8" is a Reserved Font Name for this Font Software.
   "msbm9" is a Reserved Font Name for this Font Software.
   "wncyb10" is a Reserved Font Name for this Font Software.
   "wncyi10" is a Reserved Font Name for this Font Software.
   "wncyr10" is a Reserved Font Name for this Font Software.
   "wncysc10" is a Reserved Font Name for this Font Software.
   "wncyss10" is a Reserved Font Name for this Font Software.

   This Font Software is licensed under the SIL Open Font License, Version 1.1.
   This license is copied below, and is also available with a FAQ at:
   http://scripts.sil.org/OFL

   -----------------------------------------------------------
   SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
   -----------------------------------------------------------

   PREAMBLE
   The goals of the Open Font License (OFL) are to stimulate worldwide
   development of collaborative font projects, to support the font creation
   efforts of academic and linguistic communities, and to provide a free and
   open framework in which fonts may be shared and improved in partnership
   with others.

   The OFL allows the licensed fonts to be used, studied, modified and
   redistributed freely as long as they are not sold by themselves. The
   fonts, including any derivative works, can be bundled, embedded,
   redistributed and/or sold with any software provided that any reserved
   names are not used by derivative works. The fonts and derivatives,
   however, cannot be released under any other type of license. The
   requirement for fonts to remain under this license does not apply
   to any document created using the fonts or their derivatives.

   DEFINITIONS
   "Font Software" refers to the set of files released by the Copyright
   Holder(s) under this license and clearly marked as such. This may
   include source files, build scripts and documentation.

   "Reserved Font Name" refers to any names specified as such after the
   copyright statement(s).

   "Original Version" refers to the collection of Font Software components as
   distributed by the Copyright Holder(s).

   "Modified Version" refers to any derivative made by adding to, deleting,
   or substituting -- in part or in whole -- any of the components of the
   Original Version, by changing formats or by porting the Font Software to a
   new environment.

   "Author" refers to any designer, engineer, programmer, technical
   writer or other person who contributed to the Font Software.

   PERMISSION & CONDITIONS
   Permission is hereby granted, free of charge, to any person obtaining
   a copy of the Font Software, to use, study, copy, merge, embed, modify,
   redistribute, and sell modified and unmodified copies of the Font
   Software, subject to the following conditions:

   1) Neither the Font Software nor any of its individual components,
   in Original or Modified Versions, may be sold by itself.

   2) Original or Modified Versions of the Font Software may be bundled,
   redistributed and/or sold with any software, provided that each copy
   contains the above copyright notice and this license. These can be
   included either as stand-alone text files, human-readable headers or
   in the appropriate machine-readable metadata fields within text or
   binary files as long as those fields can be easily viewed by the user.

   3) No Modified Version of the Font Software may use the Reserved Font
   Name(s) unless explicit written permission is granted by the corresponding
   Copyright Holder. This restriction only applies to the primary font name as
   presented to the users.

   4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font
   Software shall not be used to promote, endorse or advertise any
   Modified Version, except to acknowledge the contribution(s) of the
   Copyright Holder(s) and the Author(s) or with their explicit written
   permission.

   5) The Font Software, modified or unmodified, in part or in whole,
   must be distributed entirely under this license, and must not be
   distributed under any other license. The requirement for fonts to
   remain under this license does not apply to any document created
   using the Font Software.

   TERMINATION
   This license becomes null and void if any of the above conditions are
   not met.

   DISCLAIMER
   THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
   OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
   COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
   INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
   DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
   OTHER DEALINGS IN THE FONT SOFTWARE.



 Name: BaKoMa Fonts
 Files: matplotlib/mpl-data/fonts/ttf/cm*.ttf matplotlib/mpl-data/fonts/afm/cm*.afm
 Description: Computer Modern Fonts in PostScript Type 1 and TrueType font formats.
 License: BaKoMa Fonts Licence
         BaKoMa Fonts Licence
         --------------------

     This licence covers two font packs (known as BaKoMa Fonts Collection,
     which is available at `CTAN:fonts/cm/ps-type1/bakoma/'):

       1) BaKoMa-CM (1.1/12-Nov-94)
          Computer Modern Fonts in PostScript Type 1 and TrueType font formats.

       2) BaKoMa-AMS (1.2/19-Jan-95)
          AMS TeX fonts in PostScript Type 1 and TrueType font formats.

     Copyright (C) 1994, 1995, Basil K. Malyshev. All Rights Reserved.

     Permission to copy and distribute these fonts for any purpose is
     hereby granted without fee, provided that the above copyright notice,
     author statement and this permission notice appear in all copies of
     these fonts and related documentation.

     Permission to modify and distribute modified fonts for any purpose is
     hereby granted without fee, provided that the copyright notice,

In [23]:
%pip uninstall matplotlib -y

Found existing installation: matplotlib 3.10.8
Uninstalling matplotlib-3.10.8:
  Successfully uninstalled matplotlib-3.10.8
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\Users\risha\AppData\Roaming\Python\Python314\site-packages\~atplotlib'.
You can safely remove it manually.

In [24]:
%pip install --upgrade matplotlib

Defaulting to user installation because normal site-packages is not writeable
Collecting matplotlib
  Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.25 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.2-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   -- ------------------------------------- 0.5/9.5 MB 37.7 kB/s eta 0:03:58
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   --- ------------------------------------ 0.8/9.5 MB 36.3 kB/s eta 0:04:01
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ---- ----------------------------------- 1.0/9.5 MB 33.1 kB/s eta 0:04:16
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ----- ---------------------------------- 1.3/9.5 MB 28.7 kB/s eta 0:04:46
   ------ --------------------------------- 1.6/9.5 MB 27.8 kB/s eta 0:04:45

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
%pip install --upgrade seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from seaborn) (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\risha\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
df1["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [33]:
total=df1["Name"].count()
print(total)

891

In [35]:
pd.crosstab(df1["Sex"], df1["Survived"], normalize="index")

Survived         0         1
Sex
female    0.257962  0.742038
male      0.811092  0.188908

In [36]:
pd.crosstab(df1["Pclass"], df1["Survived"], normalize="index")

Survived         0         1
Pclass
1         0.370370  0.629630
2         0.527174  0.472826
3         0.757637  0.242363

In [37]:
pd.crosstab(df1["Embarked"], df1["Survived"], normalize="index")

Survived         0         1
Embarked
C         0.446429  0.553571
Q         0.610390  0.389610
S         0.663043  0.336957

In [38]:
pd.crosstab([
    df1["Sex"],df1["Pclass"]],
    df1["Survived"],
    normalize="index"
)

Survived              0         1
Sex    Pclass
female 1       0.031915  0.968085
       2       0.078947  0.921053
       3       0.500000  0.500000
male   1       0.631148  0.368852
       2       0.842593  0.157407
       3       0.864553  0.135447

In [39]:
pd.crosstab([
    df1["Sex"],df1["Pclass"],df1["Embarked"]],
    df1["Survived"],
    normalize="index"
)

Survived                       0         1
Sex    Pclass Embarked
female 1      C         0.023256  0.976744
              Q         0.000000  1.000000
              S         0.041667  0.958333
       2      C         0.000000  1.000000
              Q         0.000000  1.000000
              S         0.089552  0.910448
       3      C         0.347826  0.652174
              Q         0.272727  0.727273
              S         0.625000  0.375000
male   1      C         0.595238  0.404762
              Q         1.000000  0.000000
              S         0.645570  0.354430
       2      C         0.800000  0.200000
              Q         1.000000  0.000000
              S         0.845361  0.154639
       3      C         0.767442  0.232558
              Q         0.923077  0.076923
              S         0.871698  0.128302

In [40]:
df1.groupby('Survived')[['Age','Fare','SibSp',"Parch"]].mean()

                Age       Fare     SibSp     Parch
Survived
0         30.626179  22.117887  0.553734  0.329690
1         28.343690  48.395408  0.473684  0.464912

In [43]:
df1.groupby('Survived')[['Age','Fare','SibSp',"Parch"]].median()

           Age  Fare  SibSp  Parch
Survived
0         28.0  10.5    0.0    0.0
1         28.0  26.0    0.0    0.0

In [44]:
pd.crosstab(df1["SibSp"], df1["Survived"], normalize="index")

Survived         0         1
SibSp
0         0.654605  0.345395
1         0.464115  0.535885
2         0.535714  0.464286
3         0.750000  0.250000
4         0.833333  0.166667
5         1.000000  0.000000
8         1.000000  0.000000

In [45]:
pd.crosstab(df1["Parch"], df1["Survived"], normalize="index")

Survived         0         1
Parch
0         0.656342  0.343658
1         0.449153  0.550847
2         0.500000  0.500000
3         0.400000  0.600000
4         1.000000  0.000000
5         0.800000  0.200000
6         1.000000  0.000000

In [47]:
df1['AgeGroup']=pd.cut(
    df1['Age'],
    bins=[0,12,18,30,50,80],
    labels=['Child','Teenager','Young Adult','Adult','Senior']
)

In [48]:
pd.crosstab(df1["AgeGroup"],df1["Survived"],normalize="index")

Survived            0         1
AgeGroup
Child        0.420290  0.579710
Teenager     0.571429  0.428571
Young Adult  0.644444  0.355556
Adult        0.576763  0.423237
Senior       0.656250  0.343750

In [49]:
df1["HasCabin"] = df1["Cabin"].notna().astype(int)

pd.crosstab(
    df1["HasCabin"],
    df1["Survived"],
    normalize="index"
)

Survived         0         1
HasCabin
0         0.700146  0.299854
1         0.333333  0.666667

In [ ]:
from sklearn.model_selection import train_test_split
X=df1.drop("Survived",axis=1)
y=df1["Survived"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

In [52]:
X_train.shape, X_test.shape

((712, 13), (179, 13))

In [54]:
y_train.value_counts(normalize=True)

Survived
0    0.623596
1    0.376404
Name: proportion, dtype: float64

In [55]:
y_test.value_counts(normalize=True)

Survived
0    0.586592
1    0.413408
Name: proportion, dtype: float64

In [56]:
features = [
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked"
]

X_train = X_train[features]
X_test = X_test[features]

In [57]:
numeric_features = [
    "Pclass",
    "Age",
    "SibSp",
    "Parch",
    "Fare"
]

categorical_features = [
    "Sex",
    "Embarked"
]

In [58]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [60]:
numeric_pipeline=Pipeline([
    ("imputer",SimpleImputer(strategy="median"))
])

In [61]:
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [62]:
preprocessor=ColumnTransformer([
    ("num",numeric_pipeline,numeric_features),
    ("cat",categorical_pipeline,categorical_features)
])

In [63]:
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [64]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Pclass', 'Age', 'SibSp',
                                                   'Parch', 'Fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [65]:
y_pred = model.predict(X_test)

In [66]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Baseline Accuracy:", accuracy)

Baseline Accuracy: 0.8100558659217877

In [67]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[90 15]
 [19 55]]

In [68]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

In [70]:
import joblib

joblib.dump(model, "../model/baseline_logistic_regression.pkl")

['../model/baseline_logistic_regression.pkl']